### ISSUE TITLE
First Design without FAQ, Contact and Footer

### ISSUE THREAD

**Issue by Jubeki** [tiadal/pro-students.de#3]
![first_design_it_courses_for_companies](https://user-images.githubusercontent.com/15707543/102923746-958da700-4490-11eb-9a33-97e2d1529034.jpg)

@FM-2018 please provide some feedback for the first design.

FAQ, Contact and Footer Section will later be added.

**Comment by FM-2018** [comment]
This design seems clean, warm and professional. If that's the ambiance @tiadal  and @pre-step are looking for, then I think it makes for a very good design once Footer, FAQ and Contact are added. I do notice that one of the requested colors (#7EBDC2) isn't used here.  We should probably work on including it somewhere into the design. It stands out quite a bit in regards to the rest of the site's colors, so I think we could use it for another type of call to action, maybe. Possibly for the contact form?

@tiadal , @pre-step , what do you think about the general look and feel of the design? We'll do some work in completing the design with FAQ and footer soon, but I think it'd be important to know whether you are fine with the "corporate" feel of our current approach.
 In addition, as you can see, we're supplying quite a few illustrations of our own.  Are you fine with this, or do you insist we use certain sample images you deem important from your PDF regarding the pages? I'm especially referring to the pictures in your "About us" page, which seem more down-to-earth and less suitable for a "professional" design like this one. Maybe workarounds can be found (No pictures of you? You provide more "professional" pictures? We use illustrated avatars for each of you? Something else?)

**Comment by Jubeki** [comment]
So in this example there are the FAQ, contact and footer added. Also some alignment issues are fixed. The header illustration was also changed.

![it_courses_for_companies html](https://user-images.githubusercontent.com/15707543/102934216-05595d00-44a4-11eb-9c71-23759a6ccf62.png)

In your description it says that you want your Mission / Vision in the footer therefor here is an alternate footer without the social media icons.

![Group 3](https://user-images.githubusercontent.com/15707543/102934256-1013f200-44a4-11eb-9e52-57acc4abd28d.png)

We are now using all of your requested colors and are hoping that you like the given design.

**Comment by tiadal** [comment]
Hello @Jubeki, hello @FM-2018,

first of all, great job. You perfectly matched colors and sections.

**HEADER**
Fine, once testing make sure it's responsive and that the dropdown behavior is working.

**MAIN** 
I like the style. Do you have any idea regarding the mobile version? 
You can start opening issues regarding each page or make a project here on git so we can move on.

**FOOTER**
Mission / Vision is correct, you can also create a version that has both icons and text, IF you manage it otherwise Low Prio.
FAQ, Contact, Footer itself: must be on all pages.

Thanks,
Mattia

**Comment by FM-2018** [comment]
Hello @tiadal and @pre-step , 

we're glad to hear you like the design!  That means we can get started on the actual implementation relatively soon. We'll probably begin with the desktop version and handle responsiveness (i.e. different screen sizes) later on. The mobile versions are still to be designed, however they shouldn't differ too much from what you can see here, as sections are already stacked vertically. But of course, text and images probably cannot be side by side in the mobile version. We'll report back to you once we have agreed on a design here.

Many of the pages are going to look quite similar to one another (e.g. the various course-list pages, or the legal pages). I suggest we open issues thematically rather than exactly by-page to avoid redundancy. We'll see what works best once we can provide first results. For now, let's close this issue.

Once again, merry Christmas to you!
Julius & Fabian
