### ISSUE TITLE
Logo suggestion and SVG creation

### ISSUE THREAD

**Issue by Jubeki** [tiadal/pro-students.de#4]
![cf837ed1-9fff-4f8e-a0ff-07acf25da985_200x200 1](https://user-images.githubusercontent.com/15707543/102925074-05049600-4493-11eb-9a22-e93b0fee1b2b.png)

Hey @tiadal and @pre-step ,

we created a placeholder logo and want to ask if it is okay if we continue in using it and to convert it into the svg format.

@FM-2018 would you do that then?

**Comment by FM-2018** [comment]
Hey there,

With commits 164d3f0, bb6f07a and b705e59, I've created three SVG versions of this logo. Version one stays quite true to the original:
![Logo alternative 1](docs/img/logo-alt1.svg)

Version two has a slightly reduced spacing:
![Logo alternative 2](docs/img/logo-alt2.svg)

And the final version shows the graphical illustration on the left more  prominently:
![Logo alternative 3][docs/img/logo-alt3.svg]

All of these versions can be found in the [img subdirectory](docs/img) of the docs directory, labeled logo-alt1 through logo-alt3.

@tiadal  and @pre-step , do you prefer any of the versions I've presented here? In general, are you fine with the logo we're suggesting or do you have different ideas?

**Comment by Jubeki** [comment]
@FM-2018 I think you didn't export the svg right because the font family is not loaded correctly in the browser. Did you want to export it as a path? Also in your comment are images not loading. I don't know how if you can embedded them in these issues.

**Comment by FM-2018** [comment]
@Jubeki I'm not sure what you mean by "not loaded correctly in the browser". Clicking the links, GitHub presents me with a rendered png version of the SVGs. You're trying to include one of them in a design already? Works on my machine (drag and drop svg file into Firefox). The font is given for the text elements as part of the style attribute. I suggest in the final solution we'll solve that part using IDs and CSS, but that seem overkill right now (unless such a change causes the SVG to work on your end)

Regarding embedding images, yeah, GitHub says it doesn't support SVG for upload (and probably for embedding). I'd have to export each SVG as png and embed that here, since GitHub doesn't seem to manage that automatically for some reason. Will do.

**Comment by Jubeki** [comment]
It seems like now is Github loading the right preview. It was not working before for me...

**Comment by tiadal** [comment]
Hello @FM-2018 hello @Jubeki,

thanks for it. The Logo is beautiful, please go wit: Version two (has a slightly reduced spacing)

Please make sure in the final version, that the Logo and all images are displayed correctly on the browsers.

Merry Christmas,
Mattia

**Comment by FM-2018** [comment]
Alright, great! Then we'll integrate that logo version into the design soon. 

Merry Christmas!
Julius & Fabian
